# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support.ui import Select




class SegmentationVolbrain():
  def setup_method(self):
    options = webdriver.ChromeOptions()
    options.add_argument("headless")
    self.driver = webdriver.Chrome('chromedriver.exe', chrome_options=options)
    self.vars = {}

  def teardown_method(self):
    self.driver.quit()

  def submit_volbrain(self, dir, sexo, idade):
    self.driver.get("https://volbrain.upv.es/index.php")
    self.driver.set_window_size(1107, 680)
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("alzheimeranalysis@gmail.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("alzheimer123")
    self.driver.find_element(By.NAME, "sub").click()
    self.driver.find_element(By.ID, "pipeline4").click()
    self.driver.execute_script("document.getElementById('modality1').click()")
    self.driver.find_element(By.ID, "hips_mt1_file").send_keys(dir)
    self.driver.execute_script("document.getElementById('hips_patientssex_t1').click()")
    select = Select(self.driver.find_element_by_id("hips_patientssex_t1"))
    select.select_by_visible_text(sexo)
    self.driver.find_element(By.ID, "hips_patientssex_t1").click()
    self.driver.find_element(By.ID, "hips_patientsage_t1").click()
    self.driver.find_element(By.ID, "hips_patientsage_t1").send_keys(idade)
    self.driver.find_element(By.ID, "protocol1_t1").click()
    self.driver.find_element(By.NAME, "button_hips_t1").click()
    time.sleep(100)
