# Generated by Django 2.2.6 on 2019-11-14 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191113_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='alzheimer',
            name='status_seg',
            field=models.CharField(choices=[('0', 'Erro'), ('1', 'Processando'), ('2', 'Consluído')], default='1', max_length=20),
        ),
        migrations.DeleteModel(
            name='Status_segmentacao',
        ),
    ]
