# Generated by Django 3.0.5 on 2020-05-31 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='alzheimer',
            name='resultado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alzheimer',
            name='sexo',
            field=models.CharField(choices=[('Female', 'Feminino'), ('Male', 'Masculino')], max_length=15),
        ),
    ]
