# Generated by Django 3.0.5 on 2020-06-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alzheimer_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alzheimer',
            name='folder',
            field=models.CharField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='alzheimer',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='alzheimer',
            name='status_seg',
            field=models.CharField(choices=[('0', 'Erro'), ('1', 'Processando'), ('2', 'Concluído')], default='1', max_length=20),
        ),
    ]
