# Generated by Django 3.0.5 on 2020-06-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200604_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='alzheimer',
            name='pdf_volbrain',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
